{% set name = "yaqd-mqtt" %}
{% set version = "2021.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yaqd-mqtt-{{ version }}.tar.gz
  sha256: b18ceb7ed69a4fd81cc873872dd60378acd63aa1dbbe38d1a7c719eae1a70bc4

build:
  number: 1
  noarch: python
  entry_points:
    - yaqd-mqtt-homie-sensor = yaqd_mqtt._mqtt_homie_sensor:MQTTHomieSensor.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python {{ python_min }}
  run:
    - paho-mqtt
    - python >={{ python_min }}
    - yaqd-core >=2021.3.0
test:
  imports:
    - yaqd_mqtt
  commands:
    - pip check
    - yaqd-mqtt-homie-sensor --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://yaq.fyi
  summary: yaq daemons for interacting with MQTT brokers
  dev_url: https://gitlab.com/yaq/yaqd-mqtt
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
